# Generated by Django 3.2.10 on 2022-04-02 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autostop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Ссылка')),
                ('content', models.TextField(blank=True, max_length=5500, null=True, verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправления')),
                ('locations', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Точки')),
                ('locations_addresses', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Адреса точек')),
                ('rubric', multiselectfield.db.fields.MultiSelectField(choices=[('people', 'Люди'), ('animals', 'Животные'), ('good', 'Вещи'), ('food', 'Продукты'), ('others', 'Другое')], max_length=100, null=True, verbose_name='Рубрика')),
                ('seats_left', models.IntegerField(blank=True, null=True, verbose_name='Кол-во свободных мест')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'На рассмотрении'), ('rejected', 'Отклонено'), ('edited', 'Изменено'), ('archive', 'В архиве')], default='draft', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL, verbose_name='Понравившиеся публикации')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=5500, null=True, verbose_name='Комментарий')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('locations', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Точки')),
                ('locations_addresses', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Адреса точек')),
                ('status', models.CharField(choices=[('considering', 'На рассмотрении'), ('justified', 'Подтверждена'), ('rejected', 'Отклонена')], default='considering', max_length=20)),
                ('rubric', multiselectfield.db.fields.MultiSelectField(choices=[('people', 'Люди'), ('animals', 'Животные'), ('good', 'Вещи'), ('food', 'Продукты'), ('others', 'Другое')], max_length=100, null=True, verbose_name='Рубрика')),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autostop.autostop', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-published'],
            },
        ),
    ]
