# Generated by Django 3.2.10 on 2022-04-04 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autostop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerAutostop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Ссылка')),
                ('content', models.TextField(blank=True, max_length=5500, null=True, verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправления')),
                ('locations', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Точки')),
                ('locations_addresses', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Адреса точек')),
                ('rubric', multiselectfield.db.fields.MultiSelectField(choices=[('people', 'Люди'), ('animals', 'Животные'), ('good', 'Вещи'), ('food', 'Продукты'), ('others', 'Другое')], max_length=100, null=True, verbose_name='Рубрика')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'На рассмотрении'), ('rejected', 'Отклонено'), ('edited', 'Изменено'), ('archive', 'В архиве')], default='draft', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пассажир. объявление',
                'verbose_name_plural': 'Пассажир. объявления',
                'ordering': ['-published'],
            },
        ),
    ]
